[tool.poetry]
name = "pyofferup"
version = "0.1.0"
description = ""
authors = ["Daven Desai <davendesai@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
