query GetModularFeed($searchParams: [SearchParam]) {
    modularFeed(params: $searchParams) {
        analyticsData {
            requestId
            searchSessionId
            __typename
        }
        looseTiles {
            ...modularTileListing
            __typename
        }
        pageCursor
        __typename
    }
}
fragment modularTileListing on ModularFeedTileListing {
    tileId
    listing {
        ...modularListing
        __typename
    }
    tileType
    __typename
}
fragment modularListing on ModularFeedListing {
    listingId
    conditionText
    flags
    image {
        height
        url
        width
        __typename
    }
    isFirmPrice
    locationName
    price
    title
    __typename
}