query GetModularFeed($searchParams: [SearchParam], $debug: Boolean = false) {
    modularFeed(params: $searchParams, debug: $debug) {
        analyticsData {
            requestId
            searchSessionId
        }
        filters {
            ...modularFilterNumericRange
            ...modularFilterSelectionList
        }
        looseTiles {
            ...modularTileListing
        }
        pageCursor
        query {
            ...modularQueryInfo
        }
    }
}
fragment modularFilterNumericRange on ModularFeedNumericRangeFilter {
    isExpandedHighlight
    lowerBound {
        ...modularFilterNumericRangeBound
    }
    shortcutLabel
    shortcutRank
    subTitle
    targetName
    title
    type
    upperBound {
        ...modularFilterNumericRangeBound
    }
}
fragment modularFilterNumericRangeBound on ModularFeedNumericRangeFilterNumericRangeBound {
    label
    limit
    placeholderText
    targetName
    value
}
fragment modularFilterSelectionList on ModularFeedSelectionListFilter {
    targetName
    title
    subTitle
    shortcutLabel
    shortcutRank
    type
    isExpandedHighlight
    options {
        ...modularFilterSelectionListOption
    }
}
fragment modularFilterSelectionListOption on ModularFeedSelectionListFilterOption {
    isDefault
    isSelected
    label
    subLabel
    value
}
fragment modularTileListing on ModularFeedTileListing {
    tileId
    listing {
        ...modularListing
    }
    tileType
}
fragment modularListing on ModularFeedListing {
    listingId
    conditionText
    flags
    image {
        height
        url
        width
    }
    isFirmPrice
    locationName
    price
    title
    vehicleMiles
}
fragment modularQueryInfo on ModularFeedQueryInfo {
    appliedQuery
    decisionType
    originalQuery
    suggestedQuery
}