query GetModularFeed($searchParams: [SearchParam], $debug: Boolean = false) {
    modularFeed(params: $searchParams, debug: $debug) {
        analyticsData {
            requestId
            searchSessionId
        }
    }
}
